### ISSUE TITLE
Can not load data

### ISSUE THREAD

**Issue by HiepPP** [mingo-app/mingo#564]
**Describe the bug**
I am currently connected to the large database, but unfortunately, Mingo is showing the loading icon indefinitely. However, the database works fine on Mongo Compass and Robo3t.

**Screenshots**
![image](https://user-images.githubusercontent.com/8863474/233319254-bf90f0e9-8a69-48b4-93f3-4df0501db9a0.png)
![image](https://user-images.githubusercontent.com/8863474/233319493-312fb672-863f-4b5a-9a56-d3e2786a1741.png)

**Desktop (please complete the following information):**
 - Mingo version: 1.12.1
 - OS: macos

**Comment by tothradoslav** [comment]
Thank you. A large database means many collections or few collections with many documents? We have just made a change #533. So if this is related, should be solved in the next patch.

**Comment by oftoapp** [comment]
the same happens with me and my database is very small.

**Comment by tothradoslav** [comment]
Could you, guys, try this in the latest patch 1.12.2?

https://github.com/mingo-app/mingo/releases/tag/v1.12.2

We have made some more improvements, but those will be released in the next one...

**Comment by pepkin88** [comment]
I have the same issue, upgrading to 1.12.2 didn't solve it for me.

I tried to fix https://github.com/mingo-app/mingo/issues/475 by doing a factory reset and re-adding the connection from scratch, as was advised in this comment: https://github.com/mingo-app/mingo/issues/475#issuecomment-1302124506 

Unfortunately, every collection from the production database gives this infinite loader. Even small ones, with 1 or a few documents. The status bar shows correct document counts, it even says, that those documents are loaded, but they do not show in the main view.
<img width="1044" alt="image" src="https://github.com/mingo-app/mingo/assets/1028647/7b39b1ec-6cb1-4816-a731-e1edd363e2b6">

In the Aggregator tab, the documents are loaded in the preview, but the results are empty.
<img width="1034" alt="image" src="https://github.com/mingo-app/mingo/assets/1028647/5a6b1745-04e8-4a43-a990-d7c9b1824ed9">
<img width="1027" alt="image" src="https://github.com/mingo-app/mingo/assets/1028647/f9dc7fd3-0689-4087-bf96-5a32bc4cb8ac">

Similarly with NodeShell, no results.
<img width="850" alt="image" src="https://github.com/mingo-app/mingo/assets/1028647/97505a42-0c2a-4d49-a43a-74cb7f780494">

> Thank you. A large database means many collections or few collections with many documents? We have just made a change https://github.com/mingo-app/mingo/issues/533. So if this is related, should be solved in the next patch.

One of the collections has ~100M documents, so I guess it counts as a large database. And unfortunately, the newer version still has this issue (for me at least).

I also connected a dev database, no problems there.

**Comment by pepkin88** [comment]
Update: I went to Collection & Statistics and chose Actions > Refresh meta information. I waited only a few seconds and got a message "Synced". After that I could read from any collection, no problem.

So it seems, that this loading of meta information is still necessary to do anything meaningful in the app. And if a large database is connected, the app doesn't load the metadata automatically, but still requires it for most operations.

One more small thing. Even after refreshing meta information, this bubble shows missing info:
<img width="210" alt="image" src="https://github.com/mingo-app/mingo/assets/1028647/9ee03886-c789-44a3-be21-032d2659c405">

**Comment by tothradoslav** [comment]
Thank you. So after you have done the "Refresh meta information", the queries started showing results?

**Comment by pepkin88** [comment]
Yes

**Comment by tothradoslav** [comment]
Thanks, I think I found the problem. We will be releasing a new version shortly. I will notify you when the RC is out. If my solution didn't solve your problem, the RC version has DevTools enabled and i'd like to ask you to take a look inside the console to see if there are any errors listed after having this issue and sending them here.

**Comment by tothradoslav** [comment]
This has been resolved in the latest RC release, please check it out and let us know if the solution works as expected:

https://github.com/mingo-app/mingo/releases/tag/v1.13.0-rc1

**Comment by pepkin88** [comment]
I can say, that in 1.30.0-rc1 the issue with not loading documents for large databases looks fixed 🎉. After adding the connection, I can browse any collection 👍.

However, there are still some smaller related issues remaining. The current state is passable, but I don't think it is desirable.

1. Because large databases don't have the metadata automatically loaded, there's some error when opening this page:
<img width="1374" alt="Zrzut ekranu 2023-05-17 o 12 05 20" src="https://github.com/mingo-app/mingo/assets/1028647/609e6324-eb33-408d-8d8e-f0d96100d5cc">

I understand, that there's no data to show, but I'd suggest some explanation to show, informing, that it is necessary to manually execute the action "Refresh meta information".

2. Even after loading the metadata, tooltips for collections are still bugged:
<img width="214" alt="image" src="https://github.com/mingo-app/mingo/assets/1028647/d3fc2f17-4b8a-4c36-aef5-f1fb1da44150">

I tried clearing cache and restarting the program, but they still look like this.
BTW, the tooltip for the database is rendered correctly:
<img width="156" alt="image" src="https://github.com/mingo-app/mingo/assets/1028647/a3c3312a-3e8f-4251-982e-4974a86d6578">

**Comment by tothradoslav** [comment]
Thank you, we have corrected both issues now.

**Comment by pepkin88** [comment]
I tested the new version and have some feedback regarding the tooltips.

I have a main Mingo state, which has been through a lot of versions, but I also test a clean install.

After a factory reset, adding a fresh connection and refreshing meta information, unfortunately the data is not loaded into the tooltips.
<img width="381" alt="image" src="https://github.com/mingo-app/mingo/assets/1028647/2c50e5dc-70f2-44d6-a390-ce1df8c417ea">
There is also a regression, because the tooltip for database is also missing statistics:
<img width="175" alt="image" src="https://github.com/mingo-app/mingo/assets/1028647/d8783798-098b-40a5-895d-8bbcc755bbfb">

On the main Mingo state, there is some data showing, but it is old data, probably fetched with one of the previous Mingo version and saved into the session file.

But even with this out-of-date data, a small bug appeared.
It seems, that the hint about refreshing meta information show not only when the data is not loaded, but also when there is not and won't be any data to show or if the value is 0. For example: views, new/empty collections, small collections, whose size in kibibytes is rounded down to 0.
<img width="383" alt="image" src="https://github.com/mingo-app/mingo/assets/1028647/de3aef09-22aa-4870-9f17-76fd78a46105">
<img width="375" alt="image" src="https://github.com/mingo-app/mingo/assets/1028647/e8f755c1-cda4-478a-a84d-750fc156784e">
<img width="385" alt="image" src="https://github.com/mingo-app/mingo/assets/1028647/3a5c1dd7-bc75-42f6-af66-3d1c2abcf0f7">

One more small thing. I would suggest to change the message to something like "Detailed meta information not loaded due to large database size." or something reflecting the actual criteria. My database has only ~40 collections, I don't think it's that many ;)

**Comment by pepkin88** [comment]
One more thing I found, that I think might be related.

After executing "Refresh meta information", the information about indexes is cleared. By that I mean that I no longer can use the short query over an indexed field. Only when I go to the Indexes view and back to Documents, only then I can perform those shortcut queries.

**Comment by tothradoslav** [comment]
I think I solved this issue. I could not reproduce it any more. Thank you for the feedback! :)

**Comment by tothradoslav** [comment]
https://github.com/mingo-app/mingo/releases/tag/v1.13.1

**Comment by pepkin88** [comment]
@tothradoslav Thanks, it seems like all issues from this thread are fixed!

Well almost. After refreshing meta information, the tooltip values don't get updated until the next render of the collection item on the list. Most of the time it can be caused by collapsing and expanding the collection list. But for pinned collections you'd have to unpin and pin, or just restart the app.
I'd be nice, if those would rerender themself when the underlying data updates. I'm not familiar with Vue.js, so I don't know how difficult it is.
But honestly, it's a small thing, it wouldn't be that big of a deal if it stays.

**Comment by tothradoslav** [comment]
Thanks, this is corrected now, will be in next patch.

**Comment by tothradoslav** [comment]
We have just released a release candidate with this issue corrected. Please check it out here: https://github.com/mingo-app/mingo/releases/tag/v.1.13.4
